Changes in LaaP dashboard
addu390/licensing-as-a-platform pull request #3
Opened 2022-03-09 03:25 UTC by SherrinRaji

This PR includes the below changes:

1. License view list to navigate to filtered Plans within the list.
2. License view lists include icons indicating license status.
3. In-page add/edit for License and mapping to plan and feature models
4. Filters for each view list.

2022-03-10 21:55 UTC, addu390 commented on core/admin.py
> +admin.register(Plan)
Move this to the top (All the register(s) in one place)?

2022-03-10 21:56 UTC, addu390 commented on core/models.py
> +        return self.status == 'ACTIVE'
Use the constant in `constants.py`

2022-03-10 21:57 UTC, addu390 commented on core/models.py
> +    def display_license(self):
Follow the PEP8 spacing convention for the entire file.

2022-03-10 21:58 UTC, addu390 commented on core/models.py
> -    def __str__(self):
Does this look bad on the dashboard?

2022-03-10 21:59 UTC, addu390 commented
@SherrinRaji, I have reviewed the PR. Can you also add screenshot(s) here in the chat?

2022-03-10 22:00 UTC, addu390 requested changes
- PEP8 Formatting.
- Screenshot(s) of the screens.
- Use constants.py wherever necessary.

2022-03-11 05:42 UTC, SherrinRaji commented on core/admin.py
> +admin.register(Plan)
Okay sounds good!

2022-03-11 05:52 UTC, SherrinRaji commented on core/models.py
> -    def __str__(self):
Yep

2022-03-12 01:12 UTC, SherrinRaji commented
I have made the changes according to your comments. 
<img width="1438" alt="Screenshot 2022-03-11 at 20 57 53" src="https://user-images.githubusercontent.com/17095309/157997518-b48faa63-247c-4f08-b2f0-58ff7b52c49b.png">
<img width="1440" alt="Screenshot 2022-03-11 at 20 58 15" src="https://user-images.githubusercontent.com/17095309/157997524-bb14f083-88f3-49a2-b196-7532bfe36e52.png">

2022-03-12 03:53 UTC, addu390 commented on core/admin.py
> +from django.db.models import *
Avoid using `*` import(s), import what's necessary.

2022-03-12 03:55 UTC, addu390 commented on core/constants.py
> +ACTIVE_STATUS = 'ACTIVE'
There's already a constant called `ACTIVE `, why is this required?

2022-03-12 03:57 UTC, addu390 requested changes
LGTM, remove `ACTIVE_STATUS` in `constant.py` and import `ACTIVE` instead.

2022-03-14 19:39 UTC, addu390 commented on core/models.py
> +    def license_status(self):
What's this for?

2022-03-14 19:42 UTC, addu390 commented on core/models.py
> +    def display_plan(self):
What's this for?

2022-03-14 19:42 UTC, addu390 commented on core/models.py
> +    def display_license(self):
PEP8 is not used again.

2022-03-14 19:43 UTC, addu390 commented on core/models.py
> +    def display_feature(self):
Looks like a lot of code duplicate for display, what is this for in the Admin Panel?

2022-03-14 19:43 UTC, addu390 requested changes
Code duplication?

2022-03-14 22:44 UTC, addu390 approved these changes
LGTM

2022-03-14 22:45 UTC, merged